# Generated by Django 5.0.7 on 2024-08-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employees',
            field=models.ManyToManyField(related_name='employees', to='UserApp.employee'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserApp.project'),
        ),
    ]
