# Generated by Django 5.0.7 on 2024-08-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_task_employees_alter_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='checkIn_location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='checkOut_location',
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkIn_location_lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkIn_location_long',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkOut_location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkOut_location_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
