# Generated by Django 5.0.7 on 2024-08-14 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_remove_attendance_checkin_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.shifts'),
        ),
    ]
