# Generated by Django 5.0.7 on 2024-08-15 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_employee_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkIn_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkOut_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkIn_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkOut_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
